// Sample data — based on "Attention Is All You Need"

const SEGMENTS = [
  { t: 0, end: 28, title: "Cold open: Why translate word-by-word fails", thumb: "scene-cold" },
  { t: 28, end: 76, title: "The recurrent bottleneck", thumb: "scene-rnn" },
  { t: 76, end: 142, title: "Queries, Keys, Values — an analogy", thumb: "scene-qkv" },
  { t: 142, end: 218, title: "Scaled dot-product, derived from scratch", thumb: "scene-dot" },
  { t: 218, end: 296, title: "The softmax: a soft argmax", thumb: "scene-softmax" },
  { t: 296, end: 384, title: "Multi-head: looking many ways at once", thumb: "scene-mh" },
  { t: 384, end: 462, title: "Positional encoding: where am I?", thumb: "scene-pos" },
  { t: 462, end: 540, title: "Putting it together: the encoder block", thumb: "scene-block" },
  { t: 540, end: 612, title: "Worked example: 'the cat sat'", thumb: "scene-cat" },
  { t: 612, end: 678, title: "What's next: scaling laws", thumb: "scene-next" },
];

const TRANSCRIPT = [
  { t: 0, text: "Imagine you're translating a sentence from French to English." },
  { t: 4, text: "Word by word, left to right, never looking back." },
  { t: 8, text: "It works — until it doesn't." },
  { t: 12, text: "Take this sentence: 'The animal didn't cross the street because it was too tired.'" },
  { t: 18, text: "What does 'it' refer to? The animal — but you can only know that by looking at the whole sentence at once." },
  { t: 26, text: "Recurrent networks process tokens in sequence, carrying a hidden state forward." },
  { t: 32, text: "But by the time you reach 'it', the memory of 'animal' has been compressed, smeared, and partially overwritten." },
  { t: 40, text: "The 2017 paper 'Attention Is All You Need' proposes a radical alternative." },
  { t: 46, text: "Throw away recurrence entirely. Let every word look at every other word, directly." },
  { t: 54, text: "The mechanism is called self-attention, and it's beautifully simple." },
  { t: 62, text: "For every token, we compute three vectors: a query, a key, and a value." },
  { t: 70, text: "Think of it like a library." },
  { t: 76, text: "Your query is what you're looking for." },
  { t: 80, text: "Each book has a key — a label describing what it contains." },
  { t: 86, text: "And a value — the actual content inside." },
  { t: 92, text: "You match your query against every key, and pull out a weighted blend of values." },
  { t: 100, text: "The matching score is just a dot product: query dot key." },
  { t: 108, text: "Higher dot product means more aligned, means more relevant." },
  { t: 114, text: "But there's a problem. As dimensions grow, dot products grow too — and the softmax saturates." },
  { t: 124, text: "So we scale by the square root of d_k. That's the 'scaled' in scaled dot-product attention." },
  { t: 134, text: "Now we apply softmax to turn scores into probabilities." },
  { t: 142, text: "Softmax is just a soft argmax: it picks a winner, but smoothly." },
  { t: 150, text: "And finally, we use those probabilities to take a weighted average of the values." },
  { t: 158, text: "That's it. That's the whole mechanism." },
];

// Five stages tracked for segment 1 only. After segment 1 is ready,
// the UI switches to "Preparing segment X" cards for segments 2..N.
const PIPELINE_STAGES = [
  { id: "explanation", name: "Explanation", desc: "Reading the paper, planning segments", icon: "doc" },
  { id: "audio", name: "Audio", desc: "Narrating every beat", icon: "sparkle" },
  { id: "codegen", name: "Codegen", desc: "Writing the Manim animation", icon: "code" },
  { id: "render", name: "Render", desc: "Rendering frames", icon: "film" },
  { id: "sync", name: "Sync", desc: "Matching audio to video", icon: "brain" },
];

const LIVE_LOG = [
  { stage: "extract", text: "Detected ToC: 7 sections, 1 paper" },
  { stage: "extract", text: "Stripped: references, appendix A, footnotes" },
  { stage: "extract", text: "Chapter 1: 'Introduction' — 1,847 tokens" },
  { stage: "extract", text: "Chapter 2: 'Background' — 2,103 tokens" },
  { stage: "extract", text: "Chapter 3: 'Model Architecture' — 4,892 tokens" },
  { stage: "digest", text: "Identified 14 core concepts" },
  { stage: "digest", text: "Equations: 7 (with derivations)" },
  { stage: "digest", text: "Worked examples: 'cat sat' chosen as running example" },
  { stage: "digest", text: "Series Bible: notation locked (Q, K, V, d_k)" },
  { stage: "explain", text: "Drafting cold open: 'pronoun resolution puzzle'" },
  { stage: "explain", text: "Beat 1: motivation (28s)" },
  { stage: "explain", text: "Beat 2: recurrence problem (48s)" },
  { stage: "explain", text: "Beat 3: QKV intro — library analogy (66s)" },
  { stage: "explain", text: "Difficulty mode: TECHNICAL — keeping √d_k derivation" },
  { stage: "manim", text: "Scene 01: arrow_diagram, 4 mobjects" },
  { stage: "manim", text: "Scene 02: rnn_unfold, 12 mobjects" },
  { stage: "manim", text: "Validator: fixed 2 overlap warnings" },
  { stage: "manim", text: "Scene 06: matrix_mul, bounds OK" },
  { stage: "render", text: "TTS: voice 'aria_v3' — 11 beats queued" },
  { stage: "render", text: "Rendering scene 01 @ 1080p…" },
  { stage: "render", text: "Rendering scene 02 @ 1080p…" },
  { stage: "render", text: "Encoding: H.264, 8000kbps" },
  { stage: "render", text: "Stitching audio + video tracks" },
];

const LIBRARY = [
  {
    id: "attn",
    title: "Attention Is All You Need",
    author: "Vaswani et al., 2017",
    duration: "11:18",
    mode: "Technical",
    status: "ready",
    progress: 100,
    created: "2 hours ago",
    series: "Transformers from First Principles",
    chapter: "1 of 6",
    accent: "var(--accent-2)",
  },
  {
    id: "bert",
    title: "BERT: Pre-training of Deep Bidirectional Transformers",
    author: "Devlin et al., 2019",
    duration: "14:02",
    mode: "Technical",
    status: "ready",
    progress: 100,
    created: "Yesterday",
    series: "Transformers from First Principles",
    chapter: "2 of 6",
    accent: "var(--accent)",
  },
  {
    id: "gan",
    title: "Generative Adversarial Nets",
    author: "Goodfellow et al., 2014",
    duration: "9:47",
    mode: "Easy",
    status: "ready",
    progress: 100,
    created: "3 days ago",
    series: null,
    chapter: null,
    accent: "var(--accent-warm)",
  },
  {
    id: "diffusion",
    title: "Denoising Diffusion Probabilistic Models",
    author: "Ho et al., 2020",
    duration: "—",
    mode: "Technical",
    status: "rendering",
    progress: 64,
    created: "Just now",
    series: null,
    chapter: null,
    accent: "var(--accent-pink)",
  },
  {
    id: "rl",
    title: "Playing Atari with Deep Reinforcement Learning",
    author: "Mnih et al., 2013",
    duration: "12:31",
    mode: "Easy",
    status: "ready",
    progress: 100,
    created: "Last week",
    series: null,
    chapter: null,
    accent: "var(--accent)",
  },
  {
    id: "fourier",
    title: "Fourier Series — Stewart, Ch. 17",
    author: "Calculus, 8e",
    duration: "18:54",
    mode: "Easy",
    status: "ready",
    progress: 100,
    created: "Last week",
    series: "Calculus, Visualized",
    chapter: "12 of 17",
    accent: "var(--accent-warm)",
  },
];

window.SEGMENTS = SEGMENTS;
window.TRANSCRIPT = TRANSCRIPT;
window.PIPELINE_STAGES = PIPELINE_STAGES;
window.LIVE_LOG = LIVE_LOG;
window.LIBRARY = LIBRARY;
